name: app_gastos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  provider:       ^6.1.5
  firebase_core:  ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth:  ^4.16.0
  fl_chart:       ^1.0.0      
  english_words:  ^4.0.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
