name: app_gastos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons:
  firebase_auth: 
  firebase_core: 
  cloud_firestore: 
  provider: 

  english_words: 
  fl_chart: 
  intl: 
  intl_translation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
