/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVOQuaPhziKoBvieZIsxAPqw1ZNbXZkmQ',
    appId: '1:860991673714:web:682890cb7fff8cdf1fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    authDomain: 'aplicacion1ayl.firebaseapp.com',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    measurementId: 'G-85CSNJ7HKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWGDYf6Dq0pXVDrkydqY1fHKNJVvfMcE',
    appId: '1:860991673714:android:b326c34f2cc9a0c41fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3pQpBoEyQVgBjOohNSdgfyLO6WH31AO0',
    appId: '1:860991673714:ios:d683ca23d8205f111fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    iosBundleId: 'com.example.sportEvolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3pQpBoEyQVgBjOohNSdgfyLO6WH31AO0',
    appId: '1:860991673714:ios:d683ca23d8205f111fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    iosBundleId: 'com.example.sportEvolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVOQuaPhziKoBvieZIsxAPqw1ZNbXZkmQ',
    appId: '1:860991673714:web:0c2e41774d1142d81fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    authDomain: 'aplicacion1ayl.firebaseapp.com',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    measurementId: 'G-V08X1CWM0H',
  );
}
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
//import 'package:flutter/foundation.dart'

    //show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

///class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVOQuaPhziKoBvieZIsxAPqw1ZNbXZkmQ',
    appId: '1:860991673714:web:682890cb7fff8cdf1fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    authDomain: 'aplicacion1ayl.firebaseapp.com',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    measurementId: 'G-85CSNJ7HKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWGDYf6Dq0pXVDrkydqY1fHKNJVvfMcE',
    appId: '1:860991673714:android:b326c34f2cc9a0c41fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3pQpBoEyQVgBjOohNSdgfyLO6WH31AO0',
    appId: '1:860991673714:ios:d683ca23d8205f111fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    iosBundleId: 'com.example.sportEvolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3pQpBoEyQVgBjOohNSdgfyLO6WH31AO0',
    appId: '1:860991673714:ios:d683ca23d8205f111fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    iosBundleId: 'com.example.sportEvolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVOQuaPhziKoBvieZIsxAPqw1ZNbXZkmQ',
    appId: '1:860991673714:web:0c2e41774d1142d81fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    authDomain: 'aplicacion1ayl.firebaseapp.com',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    measurementId: 'G-V08X1CWM0H',
  );
}
/*