// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
<<<<<<< HEAD

=======
>>>>>>> origin/carolina
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
<<<<<<< HEAD
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
=======
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
>>>>>>> origin/carolina
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
<<<<<<< HEAD
        return macos;
      case TargetPlatform.windows:
        return windows;
=======
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
>>>>>>> origin/carolina
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

<<<<<<< HEAD
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVOQuaPhziKoBvieZIsxAPqw1ZNbXZkmQ',
    appId: '1:860991673714:web:682890cb7fff8cdf1fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    authDomain: 'aplicacion1ayl.firebaseapp.com',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    measurementId: 'G-85CSNJ7HKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWGDYf6Dq0pXVDrkydqY1fHKNJVvfMcE',
    appId: '1:860991673714:android:b326c34f2cc9a0c41fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3pQpBoEyQVgBjOohNSdgfyLO6WH31AO0',
    appId: '1:860991673714:ios:d683ca23d8205f111fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    iosBundleId: 'com.example.sportEvolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3pQpBoEyQVgBjOohNSdgfyLO6WH31AO0',
    appId: '1:860991673714:ios:d683ca23d8205f111fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    iosBundleId: 'com.example.sportEvolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVOQuaPhziKoBvieZIsxAPqw1ZNbXZkmQ',
    appId: '1:860991673714:web:0c2e41774d1142d81fb9eb',
    messagingSenderId: '860991673714',
    projectId: 'aplicacion1ayl',
    authDomain: 'aplicacion1ayl.firebaseapp.com',
    storageBucket: 'aplicacion1ayl.firebasestorage.app',
    measurementId: 'G-V08X1CWM0H',
=======
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1i_dPEQTFNycRKAuQ9_wugvTROLI1BM4',
    appId: '1:688988414592:android:c31c2a7fd05f942074bc65',
    messagingSenderId: '688988414592',
    projectId: 'appsports-d323a',
    storageBucket: 'appsports-d323a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCypnpw9mlopuK83F_OAedxar43GYcQz6o',
    appId: '1:688988414592:ios:d5c800198863b7dc74bc65',
    messagingSenderId: '688988414592',
    projectId: 'appsports-d323a',
    storageBucket: 'appsports-d323a.firebasestorage.app',
    iosBundleId: 'com.example.appsports',
>>>>>>> origin/carolina
  );
}
