// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJtNL-0HJqHL08jJSJ4HsBlG-q1wC6es',
    appId: '1:288927594584:web:714e9318bf162f5389b22d',
    messagingSenderId: '288927594584',
    projectId: 'controlgastos-5e467',
    authDomain: 'controlgastos-5e467.firebaseapp.com',
    storageBucket: 'controlgastos-5e467.firebasestorage.app',
    measurementId: 'G-DLWNCFW57B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwuIaZw1veeKJFrvoxampqzVvX6r96TOs',
    appId: '1:288927594584:android:200c8a3bd5fc891589b22d',
    messagingSenderId: '288927594584',
    projectId: 'controlgastos-5e467',
    storageBucket: 'controlgastos-5e467.firebasestorage.app',
  );
}
